### ISSUE TITLE
when you import from code it create a lot of ghost machines

### ISSUE THREAD

**Issue by AlonGvili** [statelyai/editor-feedback#214]
[@Flea market project _ @api _ Stately.webm](https://github.com/statelyai/studio-issues/assets/34351424/7581bdf6-77ea-4fdc-a4a1-53910c9e8c8f)

---
Studio version: 0.111.0

**Comment by kevinmaes** [comment]
Hi @AlonGvili Thanks for this feedback and for the repro video! By any chance, does the machine you're exporting and importing contain several invoked actors? If you can share the machine that would be helpful but we can also work to reproduce this on our end in the meantime and come up with a more expected solution so that it doesn't add those "ghost" machines which I understand to be rather unexpected.

**Comment by kevinmaes** [comment]
@AlonGvili For XState v5 we now export actors with `fromPromise()` or for XState v4 we export an `async` function that also returns a promise. No more "ghost" machines will be created when importing machines with invoked actors. 

However, we'll continue to think about ways to actually import invoked actor machines so that their association will be clearer in the future. Thanks again for your feedback on this issue!
