### ISSUE TITLE
Tighter integration of the editor and visualizer

### ISSUE THREAD

**Issue by jmakeig** [statelyai/editor-feedback#45]
The editor is great. It’s definitely faster and less error-prone to assemble states and transitions than JSON. I also like that it forces me to think in names for actions, guards, services, etc. rather than implementations. Even in my limited usage, I’ve saved a bunch of refactoring that I’d invariably get bogged down in in my usual depth-first implementation in code. Breadth-first with names, rather than implementations, allows me to see the plan before I dig in. 

However, as soon as you get into side effects the simulation mode in the editor starts to feel limited. The JSON export (to the clipboard, not files, thank you!) makes it easy to paste a machine definition into the visualizer. From here I can do some implementation work on actions, guards, services, etc. that I sketched out in the editor. Is there an opportunity for tighter integration than copy-paste, though? Am I missing a feature that already exists in the editor? 

Either way, kudos on both of these tools. They’re amazing. 

(Extracted from #43.)

**Comment by davidkpiano** [comment]
Glad to hear you're enjoying the editor 🙌 

The [VS Code extension](https://marketplace.visualstudio.com/items?itemName=statelyai.stately-vscode) is our first exploration of visualizing coded state machines in an editable way.

Integrating the editor and visualizer is an interesting use-case, and in the future, the editor's simulation mode will take the place of the visualizer. So, our focus is going to be on bringing simulation mode to feature parity with the visualizer rather than trying to integrate both of them.

**Comment by mattpocock** [comment]
Closing this
